language: php
php:
- 7.2
services:
- mysql
before_script:
- composer install
script: "./vendor/bin/phpunit ./tests"
deploy:
  provider: heroku
  app: curso-github-vrico
  on: master
  skip_cleanup: true
  api_key:
    secure: MOvcEQzFZKoe4gw6o83i9kCWwIr65V85tnsXKnN8v1Q3z4Nujs3QT8yYmKwrQq6UWvedvEL4OHhyNRHneX6bpiamnM1hMXmkretLzU98fZ6k+6IXo6LTqobXXh2iZFSIfzLI4CmfgU+TLoEWLJd9craYsw9Sbq9a1kWjnY5u1Q5SUwH4wvr+iKOrmbk0tIbyeRkq5EJ2lD3mGHihkbC2wYsjN96402QMXmT2OJDObZqjeUNg/Nb7dvO5K7BQ0Jd8NgVEFGm9bzWCa92+VxuVp4t7Q63AVWBTlnlNBqmeOWewWDXZPJW7rOlm1k4LwIomWtnsmUtu2qmjGg5iTVEek3O35tFBkcASBvERXhMSe4UM7cr/TXOF+qC2g8l5VAHMR2DhDmgI8RYTsY5ZRGP77GlDChGvzRRi1gKXquYk7ZI+bGjobNGcgz5YLGzFZ02CwgaESPtvXilIr0/EWhhOti7FAATLRoP3kaLIZSU/lLmWpYv5lC2fCiC+Q4xztEFYVK+OqDuMTfd2JdEnw5n8b5y5aeGZUwtPCauGQ/XJwNsWbmAQ1tb6fFFV0MjUFD2qrL9qq7BS4vO+Sh8p/YFDmHSBnvBkSINPVOtzD0ELQoY5SR2PBQBclevRi8TDMLk2G9jIQYQOe1+fxU1QNX1xCnKWF2+O7W3JPVzjMJ/HkLM=
